### PR TITLE
Update 09-UnusualParticle.md

### PR DESCRIPTION
**Pull request by UnusualParticle**
It's all coming together

### CODE REVIEW

**Comment by UnusualParticle** [comment]
## Kuzco's Poison

**Comment by UnusualParticle** [comment]
- Poisoned Kuzco
- Disposed Body
- Met a Llama
- Llama was Kuzco
- Oops

**Review by gzvm15 — APPROVED** [review]

**Review by TZR6UK — APPROVED** [review]
The poison was not real!!

**Comment by UnusualParticle** [comment]
Why do we even have that lever?!

**Pull request merged**
